INSERT ALL 
INTO GENRES(ID,GENRE_NAME) VALUES (1,'Action')
INTO GENRES(ID,GENRE_NAME) VALUES (2,'Comedy')
INTO GENRES(ID,GENRE_NAME) VALUES (3,'Drama')
INTO GENRES(ID,GENRE_NAME) VALUES (4,'Fantasy')
INTO GENRES(ID,GENRE_NAME) VALUES (5,'Horror')
INTO GENRES(ID,GENRE_NAME) VALUES (6,'Mystery')
INTO GENRES(ID,GENRE_NAME) VALUES (7,'Romance')
INTO GENRES(ID,GENRE_NAME) VALUES (8,'Thriller')
SELECT * FROM dual;


INSERT ALL 
INTO MOVIES(ID,GENRE_ID,TITLE,PRICE) VALUES (1,2,'Meet the Parents',22.50)
INTO MOVIES(ID,GENRE_ID,TITLE,PRICE) VALUES (2,2,'Mean Girls',16.50)
INTO MOVIES(ID,GENRE_ID,TITLE,PRICE) VALUES (3,4,'Jumanji',12.35)
INTO MOVIES(ID,GENRE_ID,TITLE,PRICE) VALUES (4,5,'The Babadook',11.50)
INTO MOVIES(ID,GENRE_ID,TITLE,PRICE) VALUES (5,1,'Gladiator',25.00)
INTO MOVIES(ID,GENRE_ID,TITLE,PRICE) VALUES (6,3,'Avengers: Endgame',13.50)
INTO MOVIES(ID,GENRE_ID,TITLE,PRICE) VALUES (7,7,'Moonlight',18.80)
INTO MOVIES(ID,GENRE_ID,TITLE,PRICE) VALUES (8,6,'The Usual Suspects',19.50)
INTO MOVIES(ID,GENRE_ID,TITLE,PRICE) VALUES (9,8,'Memento',22.50)
INTO MOVIES(ID,GENRE_ID,TITLE,PRICE) VALUES (10,7,'La La Land',15.50)
SELECT * FROM dual;


INSERT ALL 
INTO CUSTOMERS(ID,FIRST_NAME,LAST_NAME,EGN) VALUES (1,'Georgi','Peev','9904023940')
INTO CUSTOMERS(ID,FIRST_NAME,LAST_NAME,EGN) VALUES (2,'Ivan','Ivanov','9605076173')
INTO CUSTOMERS(ID,FIRST_NAME,LAST_NAME,EGN) VALUES (3,'Petar','Genchev','9707126764')
INTO CUSTOMERS(ID,FIRST_NAME,LAST_NAME,EGN) VALUES (4,'Martin','Hristov','9901117293')
INTO CUSTOMERS(ID,FIRST_NAME,LAST_NAME,EGN) VALUES (5,'Vladimir','Terziev','9804037544')
INTO CUSTOMERS(ID,FIRST_NAME,LAST_NAME,EGN) VALUES (6,'Daniel','Danchev','9808098176')
SELECT * FROM dual;


INSERT ALL 
INTO ORDERS(ID,CUSTOMER_ID,ORDER_DATE) VALUES (1,2,'22-MAR-06')
INTO ORDERS(ID,CUSTOMER_ID,ORDER_DATE) VALUES (2,5,'12-JUN-06')
INTO ORDERS(ID,CUSTOMER_ID,ORDER_DATE) VALUES (3,1,'02-JUN-06')
INTO ORDERS(ID,CUSTOMER_ID,ORDER_DATE) VALUES (4,3,'21-JUL-06')
INTO ORDERS(ID,CUSTOMER_ID,ORDER_DATE) VALUES (5,3,'29-AUG-06')
INTO ORDERS(ID,CUSTOMER_ID,ORDER_DATE) VALUES (6,4,'18-DEC-06')
SELECT * FROM dual;


INSERT ALL 
INTO ORDERDETAILS(ORDER_ID,MOVIE_ID) VALUES (1,4)
INTO ORDERDETAILS(ORDER_ID,MOVIE_ID) VALUES (2,6)
INTO ORDERDETAILS(ORDER_ID,MOVIE_ID) VALUES (3,8)
INTO ORDERDETAILS(ORDER_ID,MOVIE_ID) VALUES (4,3)
INTO ORDERDETAILS(ORDER_ID,MOVIE_ID) VALUES (5,9)
INTO ORDERDETAILS(ORDER_ID,MOVIE_ID) VALUES (6,5)
SELECT * FROM dual;










