CREATE VIEW FULL_INFORMATION AS
SELECT C.ID CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME, C.EGN, O.ID ORDER_ID, O.ORDER_DATE, OD.MOVIE_ID, M.TITLE, M.PRICE, G.ID GENRE_ID, G.GENRE_NAME FROM ORDERDETAILS OD
JOIN ORDERS O ON (OD.ORDER_ID = O.ID)
JOIN MOVIES M ON (OD.MOVIE_ID = M.ID)
JOIN GENRES G ON (M.GENRE_ID = G.ID)
JOIN CUSTOMERS C ON (C.ID = O.CUSTOMER_ID)
ORDER BY O.CUSTOMER_ID;

